apiVersion: v1
kind: Service
metadata:
   name: freeradius
   namespace: freeradius
   labels:
     name: freeradius
spec:
  ports:
    - name: radius-auth
      protocol: UDP
      port: 1812
      targetPort: 1812
    - name: radius-acc
      protocol: UDP
      port: 1813
      targetPort: 1813
  selector:
    app: freeradius
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: freeradius
  namespace: freeradius
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: freeradius
    spec:
      containers:
        - name: freeradius
          image: "tpdock/freeradius"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RADIUS_LISTEN_IP
              value: "*"
            - name: RADIUS_CLIENTS
              value: "SECRET@0.0.0.0/0"
          ports:
            - containerPort: 1812
              name: radauth-port
            - containerPort: 1813
              name: radacc-port


Elivate the conversation - why are we doing things

You as a pivota very good at uncovering root caused wehn customer bering you a solution - you able to drive into the root cause 
tie your approach to solve probelms to the business challenges rather than just techinal approach 

Hard skill to measure 

