apiVersion: v1
kind: Service
metadata:
   name: freeradius-pvt
   namespace: freeradius
   labels:
     name: freeradius-pvt
spec:
  ports:
    - name: radius-auth
      protocol: UDP
      port: 1812
      targetPort: 1812
    - name: radius-acc
      protocol: UDP
      port: 1813
      targetPort: 1813
  selector:
    app: freeradius-pvt
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: freeradius-pvt
  namespace: freeradius
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: freeradius-pvt
    spec:
      containers:
        - name: freeradius-pvt
          image: "harbor.gcp.pcf.space/freeradius/freeradius-ubuntu:v16.1"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RADIUS_LISTEN_IP
              value: "*"
            - name: RADIUS_CLIENTS
              value: "SECRET@0.0.0.0/0"
          ports:
            - containerPort: 1812
              name: radauth-port
            - containerPort: 1813
              name: radacc-port
